version: '3.5'
services:
 zabbix-server:
  image: zabbix/zabbix-server-pgsql:alpine-5.2-latest
  ports:
   - "10051:10051"
  restart: unless-stopped
  container_name: zabbix-server
  volumes:
   - ${dir}/zabbix-server/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ${dir}/zabbix-server/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ${dir}/zabbix-server/export:/var/lib/zabbix/export:rw
   - ${dir}/zabbix-server/modules:/var/lib/zabbix/modules:ro
   - ${dir}/zabbix-server/enc:/var/lib/zabbix/enc:ro
   - ${dir}/zabbix-server/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ${dir}/zabbix-server/mibs:/var/lib/zabbix/mibs:ro
   - ${dir}/zabbix-server/snmptraps:/var/lib/zabbix/snmptraps:ro
  links:
   - postgres-server:postgres-server
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 1G
  env_file:
   - postgres-server/.POSTGRES_CONFIG
   - zabbix-server/.ZABBIX_SERVER_CONFIG
  depends_on:
   - postgres-server
  networks:
   zbx_net_backend:
     aliases:
      - zabbix-server
      - zabbix-server-pgsql
   zbx_net_frontend:
  stop_grace_period: 30s
  labels:
   com.zabbix.description: "Zabbix server with PostgreSQL database support"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "ubuntu"

 zabbix-proxy:
  image: zabbix/zabbix-proxy-sqlite3:alpine-5.2-latest
  ports:
   - "10061:10051"
  restart: unless-stopped
  container_name: zabbix-proxy
  volumes:
   - ${dir}/zabbix-proxy/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ${dir}/zabbix-proxy/modules:/var/lib/zabbix/modules:ro
   - ${dir}/zabbix-proxy/enc:/var/lib/zabbix/enc:ro
   - ${dir}/zabbix-proxy/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ${dir}/zabbix-proxy/mibs:/var/lib/zabbix/mibs:ro
  links:
   - zabbix-server
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
  env_file:
   - zabbix-proxy/.ZABBIX_PROXY_CONFIG
   - zabbix-proxy/.SQLITE_CONFIG
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-proxy
   zbx_net_frontend:
  stop_grace_period: 30s
  labels:
   com.zabbix.description: "Zabbix proxy with SQLite3 database support"
   com.zabbix.component: "zabbix-proxy"
   com.zabbix.dbtype: "sqlite3"
   com.zabbix.os: "ubuntu"

 zabbix-frontend:
  image: zabbix/zabbix-web-apache-pgsql:5.2-alpine-latest
  ports:
   - "80:8080"
   - "443:8443"
  restart: unless-stopped
  container_name: zabbix-frontend
  links:
   - postgres-server:postgres-server
   - zabbix-server:zabbix-server
  volumes:
   - ${dir}/zabbix-frontend/ssl/apache2:/etc/ssl/apache2:ro
   - ${dir}/zabbix-frontend/modules/:/usr/share/zabbix/modules/:ro
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
  env_file:
   - postgres-server/.POSTGRES_CONFIG
   - zabbix-frontend/.ZABBIX_WEB_CONFIG
  depends_on:
   - postgres-server
   - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
   interval: 10s
   timeout: 5s
   retries: 3
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-frontend
   zbx_net_frontend:
   grafana_net_frontend:
  stop_grace_period: 10s
  labels:
   com.zabbix.description: "Zabbix frontend on Apache web-server with PostgreSQL database support"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "apache2"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "ubuntu"

 zabbix-agent:
  image: zabbix/zabbix-agent:5.2-alpine-latest
  ports:
   - "10050:10050"
  restart: unless-stopped
  container_name: zabbix-agent
  volumes:
   - ${dir}/zabbix-agent/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - ${dir}/zabbix-agent/modules:/var/lib/zabbix/modules:ro
   - ${dir}/zabbix-agent/enc:/var/lib/zabbix/enc:ro
   - ${dir}/zabbix-agent/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  links:
   - zabbix-server:zabbix-server
  deploy:
   resources:
    limits:
      cpus: '0.2'
      memory: 128M
   mode: global
  env_file:
   - zabbix-agent/.ZABBIX_AGENT_CONFIG
  privileged: true
  pid: "host"
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-agent
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix agent"
   com.zabbix.component: "zabbix-agentd"
   com.zabbix.os: "ubuntu"

 postgres-server:
  image: postgres:9.6.21-alpine
  restart: unless-stopped
  container_name: postgres-server
  volumes:
   - ${dir}/postgres-server/data:/var/lib/postgresql/data:rw
   - ${dir}/postgres-server/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
   - ${dir}/postgres-server/.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
   - ${dir}/postgres-server/.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
   - ${dir}/postgres-server/docker-entrypoint-initdb.d/multiples-db.sh:/docker-entrypoint-initdb.d/multiples-db.sh
  env_file:
   - postgres-server/.POSTGRES_CONFIG
  stop_grace_period: 1m
  networks:
   zbx_net_backend:
    aliases:
     - postgres-server
     - pgsql-server
     - pgsql-database

 grafana-server:
    image: grafana/grafana:7.5.3
    container_name: grafana-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      grafana_net_frontend:
      zbx_net_backend:

    depends_on:
      - zabbix-server
      - postgres-server
    links:
      - zabbix-server
      - postgres-server
    volumes:
      - ${dir}/grafana-server/lib/grafana:/var/lib/grafana
      - ${dir}/grafana-server/conf:/usr/share/grafana/conf
      - ${dir}/grafana-server/log/grafana:/var/log/grafana
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app, simpod-json-datasource
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_LOG_MODE=console file
      - GF_LOG_LEVEL=info

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.27.238.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.27.239.0/24
  grafana_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.27.240.0/24